version: '3.7'
services:
  postgres:
    image: postgres:11
    env_file: .env
    volumes:
    - ~/.volume-data/wreeto_official/postgres-data:/var/lib/postgresql/data
  app:
    image: chrisvel/wreeto:latest
    command: foreman start 
    volumes:
      - .:/app/wreeto
      - ./public/assets:/app/wreeto/public/assets
      - ./storage:/app/storage
      - ./backups:/app/backups
    ports:
      - 8383:8383
    depends_on:
      - postgres
      - redis
    env_file: .env      
  redis:
    image: redis:5.0.7
